[[rule]]
include = ["pack.toml"]

[rule.schema]
path = "./packwiz-schemas/src/schemas/json/packwiz-pack.json"

[[rule]]
include = ["**/*.pw.toml"]

[rule.schema]
path = "./packwiz-schemas/src/schemas/json/packwiz-mod.json"

[[rule]]
include = ["**/index.toml"]

[rule.schema]
path = "./packwiz-schemas/src/schemas/json/packwiz-index.json"
