name = "Meow"
author = "fea"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "./content/index.toml"
hash-format = "sha256"
hash = "1f7190e459663696aef62438b33c58b28d0b8daa0fa9f97d95e29f29f896a4ed"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.128"

[options]
datapack-folder = "config/paxi/datapacks"
meta-folder-base = "./content"
