name = "Meow"
author = "fea"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "./content/index.toml"
hash-format = "sha256"
hash = "a952b02f5c8f75406e093b1702a23d5f2c0fa3463ba183502f55a9354f05bea6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.129"

[options]
datapack-folder = "config/paxi/datapacks"
meta-folder-base = "./content"
