name = "Meow"
author = "fea"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "./content/index.toml"
hash-format = "sha256"
hash = "2e360811c4794b12fa5a305db6ac2679b8cb328294c57515e50d6813aba4844e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.129"

[options]
datapack-folder = "config/paxi/datapacks"
meta-folder-base = "./content"
