name = "Meow"
author = "fea"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "./content/index.toml"
hash-format = "sha256"
hash = "e0340cf341ce003ec825a223cc3314a7cfcd943cff4ec2217bf1e7d9f02bfbc6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.129"

[options]
datapack-folder = "config/paxi/datapacks"
meta-folder-base = "./content"
