name = "Meow"
author = "fea"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "./content/index.toml"
hash-format = "sha256"
hash = "9b7ceb83d60845ece7fd5cdf5f82613631f4062e862fb1fb69c5c6ec44ce4c00"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.128"

[options]
datapack-folder = "config/paxi/datapacks"
meta-folder-base = "./content"
