name = "Meow"
author = "fea"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "./content/index.toml"
hash-format = "sha256"
hash = "1c82261556178dcf86e8c8f1c0409eeea6d50bd81e4e5450c1ac9e972a489b32"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.129"

[options]
datapack-folder = "config/paxi/datapacks"
meta-folder-base = "./content"
